build:
	go build -o bin/checkup ./cmd/checkup

run:
	./checkup

run-email:
	./checkup --email

run-users:
	./checkup --users

run-monitors:
	./checkup --monitors

run-database:
	./checkup --database

run-help:
	./checkup --help

clean:
	rm -f checkup

.PHONY: build run run-email run-users run-monitors run-database run-help clean
